version: '3.7'
services:
    backend:
        build: .
        container_name: backend
        restart: on-failure
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            database:
                condition: service_healthy
    database:
        image: mysql:latest
        container_name: database
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: app_db
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./entrypoint/:/docker-entrypoint-initdb.d/:ro
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    nuxt:
        build: ./nuxt
        container_name: nuxt
        restart: on-failure
        ports:
            - "3000:3000"
        depends_on:
            - backend
volumes:
    mysql-data: